apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    indexHtml: |-
      <!DOCTYPE html>
        <html>
        <head>
          <title>My Custom Page</title>
        </head>
        <body>
          <h1>Welcome to my custom NGINX page</h1>
        </body>
        </html>
